### ISSUE TITLE
To-Do (Week of Nov 29)

### ISSUE THREAD

**Issue by maarinku** [maarinku/RE-Zekot#1]
- [ ] Create interactions handler
- [ ] Finish `help.js` with interactions and ephemerals
- [ ] Create pp.js
- [ ] Create info.js
- [ ] Create staff.js
- [ ] Create av.js
- [ ] Create afk.js
- [ ] Create vote.js
